### ISSUE TITLE
IntelliJ code inspection: 1423 errors, 21796 warnings

### ISSUE THREAD

**Issue by nikitakoselev** [finbourne/lusid-sdk-java-preview#133]
![image](https://user-images.githubusercontent.com/6383738/172959608-8a88780e-f806-4582-9055-b44cf494c934.png)

Probably the code was autogenerated, which explains everything.
If the code was autogenerated - close the bug, please.

## Bug Report Checklist

**SDK version**
0.11.4456-SNAPSHOT

**Describe the bug**
IntelliJ inspection shows 1423 errors. Most of them are not that serious, but there are 10 security warnings.

**To Reproduce**
Open the project in the IntelliJ professional, run Code->Inspect Code

**Expected behavior**
A number of warnings are expected to be produced.
Ideally, there shall be none, but we live in the real world.

**Additional context**
Zip file. HTML is easier to watch, and XML (probably) can be imported to IntelliJ (needs to be confirmed).
[intellij-code-inspection.zip](https://github.com/finbourne/lusid-sdk-java-preview/files/8874440/intellij-code-inspection.zip)

The big picture:
![image](https://user-images.githubusercontent.com/6383738/172959903-c95aec75-ee7d-4196-aa6d-53169684ff4e.png)

**Comment by rizwansaeed** [comment]
Hi Nikita, the sdks are indeed code generated using https://github.com/OpenAPITools/openapi-generator and so we would need to raise PRs to fix the underlying issues in that project
